CREATE TABLE POKEMON (ID INT PRIMARY KEY,
                    NAME VARCHAR(25),
                    TYPE VARCHAR(25) );


CREATE TABLE TRAINER (ID INT PRIMARY KEY,
                    NAME VARCHAR(25),
                    LEVEL INT);
--CREATE TABLE POKEMONTRAINER (TRAINER_ID INT ,
--                    POKEMON_ID INT ,
--                     FOREIGN KEY(TRAINER_ID),
--                     FOREIGN KEY(POKEMON_ID)
--                    primary key (TRAINER_ID, POKEMON_ID));
--



CREATE TABLE POKEMONTRAINER (
  TRAINER_ID INT NOT NULL,
  POKEMON_ID INT NOT NULL,
  PRIMARY KEY ( TRAINER_ID, POKEMON_ID),
  CONSTRAINT `POKEMON_ID`
    FOREIGN KEY (`POKEMON_ID`)
    REFERENCES `pokemon` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT  TRAINER_ID
    FOREIGN KEY ( TRAINER_ID)
    REFERENCES `trainer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
